env: flex
runtime: nodejs

env_variables:
  REACT_APP_URL: "https://staging.votefwd.org"
  REACT_APP_API_URL: "https://staging.votefwd.org/api"
  REACT_APP_DATABASE_URL: "postgres://scott:@localhost:5432/votefwd"
  REACT_APP_DATABASE_DIALECT: "postgres"
  REACT_APP_AUTH0_CLIENTID: "T0oLi22JFRtHPsx0595AAf8p573bxD4d"
  REACT_APP_HASHID_SALT: "q5EMmP7PaJBEXWW8cJe1jrPGDcIcLYbH"
  REACT_APP_HASHID_DICTIONARY: "23456789ABCDEFGHIJKLMNPQRSTUVWXYZ"
